[book]
authors = ["Kel (@GudEveningBois | @Scottts)"]
language = "en"
src = "src"
title = "ScriptSense Documentation"

[output.html]
additional-css = ["custom.css"]

logo = "https://raw.githubusercontent.com/Scottts/Scottts.github.io/main/assets/logo.png"
favicon = "https://raw.githubusercontent.com/Scottts/Scottts.github.io/main/assets/favicon.ico"

default-theme = "light"
preferred-dark-theme = "navy"

copy-fonts = true

