[book]
authors = ["Kel (@GudEveningBois | @Scottts)"]
language = "en"
src = "src"
title = "ScriptSense Documentation"

[output.html]
additional-css = ["custom.css"]

logo = "assets/logo.png"
favicon = "assets/favicon.ico"

default-theme = "light"
preferred-dark-theme = "navy"

copy-fonts = true

