[book]
authors = ["ScriptSense"]
language = "en"
multilingual = false
src = "src"
title = "ScriptSense Documentation"

[output.html]
additional-css = ["custom.css"]

logo = "assets/logo.png"
favicon = "assets/favicon.ico"

default-theme = "light"
preferred-dark-theme = "navy"
copy-fonts = true