[book]
authors = ["ScriptSense"]
language = "en"
multilingual = false
src = "src"
title = "ScriptSense Documentation"

[output.html]
# Apply the custom CSS
additional-css = ["src/custom.css"]

# Your assets
logo = "src/assets/logo.png"
favicon = "src/assets/favicon.ico"

# Default theme settings
default-theme = "light"
preferred-dark-theme = "navy"

# This makes the "Rojo" style search and navigation smoother
copy-fonts = true